### PR TITLE
Fix socket leak by closing HttpClient after usage

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes a socket leak that'll occur with each YouTube video checked.

I also noticed that line 23 in the testVideo.nim seems to be failing:
```nim
    check videoData.title == "Bolachinhas de GERGELIM com CEBOLA super CROCANTE"
```
because of a missing `-`. It doesn't end there - the title of the video shown on YouTube itself is "Bolachinhas de GERGELIM com CEBOLA - super CROCANTE", and if we look into the JS code of the page, it actually has two spaces before `-` instead of one:
```js
"title":{"simpleText":"Bolachinhas de GERGELIM com CEBOLA  - super CROCANTE"}
```

So I didn't modify the test as I don't know how to make a proper fix (since the data from the JS and from the YouTube page seems to differ).

### CODE REVIEW

**Comment by thisago** [comment]
Thanks for leak fix! I will check the title issue

**Comment by ghost** [comment]
Also, not really a big problem, but seems like your date settings on your PC/laptop or your Git settings are wrong?

This commit shows up as "yesterday" - https://github.com/thisago/ytextractor/commit/6dd1be734a4a1ce8853aca0552fd40534522f0a9, same as https://github.com/thisago/ytextractor/commit/3e7564a4676ee07357db545e4f3c7b022f345ec6 and some othjers

**Comment by thisago** [comment]
oh.. the utc is wrong haha. Thanks

**Comment by thisago** [comment]
the title issue is because youtube strips the spaces together... Now the title has a correct spacing.

**Pull request merged**
